name: cicd
on:
  push:
  pull_request:
  release:
    types: published
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
    - name: Build and tag Docker image
      run: make build
    - name: Login to Docker Hub
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: echo $DOCKER_HUB_TOKEN | docker login -u ascensive --password-stdin
    - name: Push to Docker Hub
      run: make push
#  release:
#    runs-on: ubuntu-latest
#    needs: ci
#    if: github.event_name == 'release'
#    steps:
#    - name: Login to Docker Hub
#      env:
#        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
#      run: echo $DOCKER_HUB_TOKEN | docker login -u ascensive --password-stdin
#    - name: Build and tag Docker image
#      run: make build
#    - name: Push to Docker Hub
#      run: make push
