name: Docker build and push
on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: published
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: ''
    - name: Build, tag, and list Docker image
      run: make build
    - name: Login to Docker Hub
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: echo $DOCKER_HUB_TOKEN | docker login -u ascensive --password-stdin
    - name: Push to Docker Hub
      run: make push
  pull_request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: ''
    - name: Build, tag, and list Docker image
      run: make build
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: ''
    - name: Build, tag, and list Docker image
      run: make build
    - name: Login to Docker Hub
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: echo $DOCKER_HUB_TOKEN | docker login -u ascensive --password-stdin
    - name: Tag and push versioned Docker image
      run: |
        set -x
        echo "$GITHUB_REF"
        GITHUB_TAG="${GITHUB_REF#refs/tags/}"
        echo "$GITHUB_TAG"
        DOCKERHUB_TAG=ascensive/irc-rss-feed-bot:"$GITHUB_TAG"
        echo "$DOCKERHUB_TAG"
        docker tag irc-rss-feed-bot "$DOCKERHUB_TAG"
        docker images
        docker push "$DOCKERHUB_TAG"
